#if 0
i18n("Water")
i18n("Formic Acid")
i18n("Acetic Acid")
i18n("Trans-Buthylene (Trans-Buthene)")
i18n("Cis-Buthylene (Cis-Buthene)")
i18n("Di-Methyl-Ether")
i18n("Buthanol (Buthylic alcohol)")
i18n("Tert-Buthanol (Tert-buthylic alcohol)")
i18n("Glycerin (1,2,3-Propane-triol)")
i18n("Poly-Tetra-Fluoro-Ethane")
i18n("Malic Acid")
i18n("Methane")
i18n("Formaldehyde")
i18n("Crystal 1")
i18n("Ethylic Acetate (Acethyl-Ethyl-Esther)")
i18n("Ammonia")
i18n("3-Methyl-Pentane")
i18n("Propyl-Aldehide (Propanal)")
i18n(" Propyne (Methyl-acetylene)")
i18n("level27")
i18n("Pyrane")
i18n("Cyclo-Pentane")
i18n("Methanol")
i18n("Nitro-Glycerin")
i18n("Ethane")
i18n("Crystal 2")
i18n("Ethylene-Glycol")
i18n("Alanine (Alpha-Amino-Propylic-Acid)")
i18n("Di-Cyan-Di-Amide")
i18n("Prussic Acid (Cyanic Acid)")
i18n("Anthracene")
i18n("Thyasole")
i18n("Zacharine")
i18n("Ethylene")
i18n("Styren")
i18n("Melamine")
i18n("Cyclo-Buthane")
i18n("Nicothine")
i18n("Acethyle-Salicylic Acid")
i18n("Meta-Di-Nitro-Benzene")
i18n("Propine")
i18n("Malonic Acid")
i18n("Di-Methyle-Propane")
i18n("Ethyl-Benzene")
i18n("Propylene (Propene)")
i18n("Asparagine")
i18n("level51")
i18n("Vanilline")
i18n("Crystal 3")
i18n("Uric Acid (?)")
i18n("Thymine")
i18n("Anyline")
i18n("Chloroform")
i18n("Carbon Dioxide")
i18n("Crystal 4")
i18n("Ethanol (Ethylic alcohol)")
i18n("Acrylo-Nitril")
i18n("Furane")
i18n("Lactic Acid")
i18n("Maleic Acid")
i18n("Acid")
i18n("Crystal 5")
i18n("Ethylic-Formiat (Formyl-Ethyl-Esther)")
i18n("Cyclo-Hexadyene")
i18n("Iso-Propanol (Isopropylic alcohol, 2-Propanol)")
i18n("Iso-Propanol (Isopropylic alcohol, 2-Propanol)")
i18n("Ethyl-aldehyde (Ethanal)")
i18n("Acetone")
#endif
